module.exports = {
  default: [
    {
      position: 0,
      mute: 0,
      lock: false,
      reserved: false,
      isSpeaking: false,
      invite: false,
      userId: null,
      name: null,
      avatarFrameImage: null,
      image: null,
      country: null,
      agoraUid: null,
    },
    {
      position: 1,
      mute: 0,
      lock: false,
      reserved: false,
      isSpeaking: false,
      invite: false,
      userId: null,
      name: null,
      avatarFrameImage: null,
      image: null,
      country: null,
      agoraUid: null,
    },
    {
      position: 2,
      mute: 0,
      lock: false,
      reserved: false,
      isSpeaking: false,
      invite: false,
      userId: null,
      name: null,
      avatarFrameImage: null,
      image: null,
      country: null,
      agoraUid: null,
    },
    {
      position: 3,
      mute: 0,
      lock: false,
      reserved: false,
      isSpeaking: false,
      invite: false,
      userId: null,
      name: null,
      avatarFrameImage: null,
      image: null,
      country: null,
      agoraUid: null,
    },
    {
      position: 4,
      mute: 0,
      lock: false,
      reserved: false,
      isSpeaking: false,
      invite: false,
      userId: null,
      name: null,
      avatarFrameImage: null,
      image: null,
      country: null,
      agoraUid: null,
    },
    {
      position: 5,
      mute: 0,
      lock: false,
      reserved: false,
      isSpeaking: false,
      invite: false,
      userId: null,
      name: null,
      avatarFrameImage: null,
      image: null,
      country: null,
      agoraUid: null,
    },
    {
      position: 6,
      mute: 0,
      lock: false,
      reserved: false,
      isSpeaking: false,
      invite: false,
      userId: null,
      name: null,
      avatarFrameImage: null,
      image: null,
      country: null,
      agoraUid: null,
    },
    {
      position: 7,
      mute: 0,
      lock: false,
      reserved: false,
      isSpeaking: false,
      invite: false,
      userId: null,
      name: null,
      avatarFrameImage: null,
      image: null,
      country: null,
      agoraUid: null,
    },
    {
      position: 8,
      mute: 0,
      lock: false,
      reserved: false,
      isSpeaking: false,
      invite: false,
      userId: null,
      name: null,
      avatarFrameImage: null,
      image: null,
      country: null,
      agoraUid: null,
    },
    {
      position: 9,
      mute: 0,
      lock: false,
      reserved: false,
      isSpeaking: false,
      invite: false,
      userId: null,
      name: null,
      avatarFrameImage: null,
      image: null,
      country: null,
      agoraUid: null,
    },
    {
      position: 10,
      mute: 0,
      lock: false,
      reserved: false,
      isSpeaking: false,
      invite: false,
      userId: null,
      name: null,
      avatarFrameImage: null,
      image: null,
      country: null,
      agoraUid: null,
    },
    {
      position: 11,
      mute: 0,
      lock: false,
      reserved: false,
      isSpeaking: false,
      invite: false,
      userId: null,
      name: null,
      avatarFrameImage: null,
      image: null,
      country: null,
      agoraUid: null,
    },
    {
      position: 12,
      mute: 0,
      lock: false,
      reserved: false,
      isSpeaking: false,
      invite: false,
      userId: null,
      name: null,
      avatarFrameImage: null,
      image: null,
      country: null,
      agoraUid: null,
    },
    {
      position: 13,
      mute: 0,
      lock: false,
      reserved: false,
      isSpeaking: false,
      invite: false,
      userId: null,
      name: null,
      avatarFrameImage: null,
      image: null,
      country: null,
      agoraUid: null,
    },
    {
      position: 14,
      mute: 0,
      lock: false,
      reserved: false,
      isSpeaking: false,
      invite: false,
      userId: null,
      name: null,
      avatarFrameImage: null,
      image: null,
      country: null,
      agoraUid: null,
    },
    {
      position: 15,
      mute: 0,
      lock: false,
      reserved: false,
      isSpeaking: false,
      invite: false,
      userId: null,
      name: null,
      avatarFrameImage: null,
      image: null,
      country: null,
      agoraUid: null,
    },
  ],
};
